export const AUDIO = {
  COUNT_IN_FREQ_ACCENT: 1000,
  COUNT_IN_FREQ_NORMAL: 800,
  COUNT_IN_GAIN: 0.4,
  COUNT_IN_DECAY: 0.06,
  METRONOME_FREQ: 800,
  METRONOME_DECAY: 0.08,
  METRONOME_SCHEDULE_AHEAD: 0.1,
  METRONOME_LOOKAHEAD_MS: 25,
} as const

export const PLAYBACK = {
  SKIP_DELTA: 5,
  SEEK_TOLERANCE: 0.5,
  COUNT_IN_BEATS: 4,
  DEFAULT_BPM: 80,
  MIN_SECTION_DURATION: 0.5,
} as const

export const UI = {
  PERSIST_DEBOUNCE_MS: 500,
  BPM_MIN: 20,
  BPM_MAX: 300,
  BPM_TAP_SESSION_SEC: 10,
  SKIP_HOLD_MS: 450,
} as const
